# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "virtio_pci" "usbhid" "usb_storage" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/ddf9279c-4d99-407e-b35d-6f67bc05f4c3";
      fsType = "btrfs";
      options = [ "compress=zstd,subvol=root" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/ddf9279c-4d99-407e-b35d-6f67bc05f4c3";
      fsType = "btrfs";
      options = [ "compress=zstd,subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/ddf9279c-4d99-407e-b35d-6f67bc05f4c3";
      fsType = "btrfs";
      options = [ "compress=zstd,subvol=nix" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/cc32433d-324e-4482-af17-d402599d2f8d"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
